
name: env-dashapp-bookreads
channels:
  - conda-forge
  - defaults
dependencies:
  - dash=2.7.0
  - dash-bootstrap-components=1.2.1
  - flask=2.2.2
  - flask-compress=1.13
  - numpy=1.23.5
  - pandas=1.5.1
  - pip=22.3.1
  - plotly=5.11.0
  - python=3.11.0
