name: env-dashapp-bookreads
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - click=8.1.3
  - colorama=0.4.6
  - dash=2.7.0
  - dash-bootstrap-components=1.2.1
  - flask=2.2.2
  - flask-compress=1.13
  - importlib-metadata=5.0.0
  - intel-openmp=2022.1.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - markupsafe=2.1.1
  - mkl=2022.1.0
  - numpy=1.23.5
  - pandas=1.5.1
  - pip=22.3.1
  - plotly=5.11.0
  - python=3.11.0
  - python_abi=3.11
  - pytz=2022.6
  - setuptools=65.5.1