
name: env-dashapp-bookreads
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates
  - click=8.1.3
  - colorama=0.4.6
  - dash=2.7.0
  - dash-bootstrap-components=1.2.1
  - flask=2.2.2
  - flask-compress=1.13
  - importlib-metadata=5.0.0
  - intel-openmp=2022.1.0
  - itsdangerous=2.1.2
  - jinja2=3.1.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - liblapack=3.9.0
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - markupsafe=2.1.1
  - mkl=2022.1.0
  - numpy=1.23.5
  - openssl=3.0.7
  - pandas=1.5.1
  - pip=22.3.1
  - plotly=5.11.0
  - python=3.11.0
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.6
  - setuptools=65.5.1
  - six=1.16.0
  - tbb=2021.7.0
  - tenacity=8.1.0
  - tk=8.6.12=
  - tzdata=2022f
  - ucrt=10.0.22621.0
  - vc=14.3
  - vs2015_runtime
  - werkzeug=2.2.2
  - wheel=0.38.4
  - xz=5.2.6
  - zipp=3.10.0
